version: '3.3'

services:

  ui:
    image: 1vshnukrshna/winesh:v14
    container_name: ui
    restart: always
    ports:                                                  
      - 3000:3000
    networks:
      - app-network                                 

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - ui
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email KrasnokutskiyEA@yandex.ru --agree-tos --no-eff-email --staging -d krasnokutsky.tech -d www.krasnokutsky.tech

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/views/
      o: bind

networks:
  app-network:
    driver: bridge 