# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run first job
      run: echo Hello, world first!

    # - name: Run a multi-line script
      # run: |
      #   echo Add other actions to build,
      #   echo test, and deploy your project.
        
  my_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run second job
      run: echo Hello, world second!

    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
