# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Docker login
      env:
        DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD

    - name: Docker build
      run: |
        docker build -t 1vshnukrshna/winesh:latest .

    - name: Docker push
      run: |
        docker push 1vshnukrshna/winesh:latest

