# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: |
        docker build -t 1vshnukrshna/winesh:latest .

    # - name: Run a multi-line script
      # run: |
      #   echo Add other actions to build,
      #   echo test, and deploy your project.

